name: harmon

services:  
  webapp:
    image: ghcr.io/danerieber/harmon-react:latest
    ports:
      - "3000:3000"
    environment:
      - SERVER_HOST
      - SERVER_PORT
      - SERVER_USES_HTTPS
      - PEER_SERVER_HOST
      - PEER_SERVER_PORT
      - PEER_SERVER_PATH
      - PEER_CONFIG

  server:
    image: ghcr.io/danerieber/harmon-server-go:latest
    ports:
      - "8080:8080"
    volumes:
      - $PWD/data:/app/data

  peerjs:
    image: peerjs/peerjs-server
    ports:
      - "9000:9000"
